# Generated by Django 2.2 on 2020-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopted',
            name='adopter',
        ),
        migrations.AddField(
            model_name='adopted',
            name='adoptername',
            field=models.CharField(default='ชื่อผู้รับเลี้ยง', max_length=100),
        ),
        migrations.AddField(
            model_name='adopted',
            name='contact',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='adopted',
            name='location',
            field=models.CharField(default='อำเภอ,จังหวัด', max_length=100),
        ),
    ]
