# Generated by Django 2.2 on 2020-04-28 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption', '0004_auto_20200428_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='request',
            name='social',
            field=models.CharField(default='FB/LINE/IG ID', max_length=70),
        ),
        migrations.AlterField(
            model_name='request',
            name='contact',
            field=models.CharField(default='หมายเลขโทรศัพท์', max_length=40),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='ข้อความ', max_length=300)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='adoption.Request')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adoption.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
