# Generated by Django 2.2 on 2020-04-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_auto_20200428_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
    ]
