# Generated by Django 2.2 on 2020-04-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_remove_message_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
