# Generated by Django 2.2 on 2020-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_remove_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('Male', 'ผู้'), ('Female', 'เมีย')], max_length=10),
        ),
    ]
