# Generated by Django 2.2 on 2020-04-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_auto_20200429_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopted',
            name='cat',
        ),
    ]
