# Generated by Django 2.2 on 2020-04-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0009_remove_adopted_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopted',
            name='cat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Cat'),
        ),
    ]
